DROP TABLE IF EXISTS Manaser;
CREATE TABLE Manager(
	uid INT PRIMARY KEY IDENTITY,
	name VARCHAR(80) NOT NULL,
	phonenum VARCHAR(20) NOT NULL,
	memo VARCHAR(max),
	regdate DATETIME DEFAULT CURRENT_TIMESTAMP
);
